booking_index:
    path:     /
    defaults: { _controller: "ReservationBundle:Booking:index" }
    methods:  GET

booking_show:
    path:     /{id}/show/
    defaults: { _controller: "ReservationBundle:Booking:show" }
    methods:  GET

booking_new:
    path:     /new/
    defaults: { _controller: "ReservationBundle:Booking:new" }
    methods:  [GET, POST]

booking_edit:
    path:     /{id}/edit/
    defaults: { _controller: "ReservationBundle:Booking:edit" }
    methods:  [GET, PUT]

booking_delete:
    path:     /{id}/delete/
    defaults: { _controller: "ReservationBundle:Booking:delete" }
    methods:  DELETE