<?php

namespace ReservationBundle\Repository;

/**
 * SummationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SummationRepository extends \Doctrine\ORM\EntityRepository
{
}
